"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fibGen(MAX):
	a,b = 0,1
	num = 0
	while True:
		if num <= MAX:
			num = a + b
			yield num
			a,b = b,num
		else:
			break


fibs = fibGen(4000000)
print sum([x for x in fibs if x % 2== 0])
